import ProductCtrl from "@/controllers/ProductCtrl";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProductLayout({ children }) {
  const categories = await ProductCtrl.categories();
  return (
    <div className="flex max-w-[1300px] mx-auto">
      <div>
        {categories.map(({ node }, index) => (
          <div key={index}>
            {node.name} ({node.count})
          </div>
        ))}
      </div>
      <div>{children}</div>
    </div>
  );
}
