import Categories from "@/components/posts/Categories";
import Tags from "@/components/posts/Tags";
import db from "@/lib/cache";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PostsLayout({ children }) {
  const categories = await db.PostsCategories();
  const tags = await db.PostsTags();
  if (!categories) {
    notFound();
  }
  return (
    <div className="flex max-w-[1300px] mx-auto">
      <Categories initialData={categories} />
      <div>{children}</div>
      <Tags initialData={tags} />
    </div>
  );
}
