
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function PostsLayout({ children }) {
  return (
    <div className="flex max-w-[1300px] mx-auto">
       <div>{children}</div>
    </div>
  )
}
