import Categories from "@/components/posts/Categories";
import { fetchAllCursors } from "@/lib/fetchAllCursors";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PostsLayout({ children }) {
  const { categories } = await fetchAllCursors();
  if (!categories) {
    notFound();
  }
  return (
    <div className="flex max-w-[1300px] mx-auto">
      <Categories initialData={categories} />
      <div>{children}</div>
    </div>
  );
}
