name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Hoặc tên nhánh bạn muốn theo dõi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Sử dụng phiên bản Node.js phù hợp

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Cần thiết lập token trong Secrets
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Cần thiết lập account ID trong Secrets
          project-name: jam3  # Tên project trên Cloudflare Pages
          directory: out  # Thư mục chứa các tệp đã build
